import React from 'react';
import { ScrollView, Text } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import LessonContent from '../components/LessonContent';
const sections = [
  ['Numbers and conversions', 'Integer division truncates toward zero. Cast before division to keep a fraction. % computes a remainder; it is not a percentage.', 'int quotient = 7 / 2;             // 3\ndouble mean = (double) 7 / 2;     // 3.5\nint digit = 37 % 10;              // 7'],
  ['Math methods', 'Math methods are static. random returns a double at least 0.0 and less than 1.0. Scale before casting to an integer.', 'Math.abs(-5);                    // 5\nMath.sqrt(49.0);                 // 7.0\nMath.pow(2.0, 4.0);              // 16.0\n(int) (Math.random() * 6) + 1;    // integer 1 through 6'],
  ['String methods', 'String is immutable. substring includes the starting index and excludes the ending index. equals compares contents; compareTo gives a sign indicating lexicographic order.', 'String s = "coding";\ns.length();                     // 6\ns.substring(1, 4);              // "odi"\ns.substring(3);                 // "ing"\ns.indexOf("di");                // 2\ns.indexOf("x");                 // -1\ns.equals("coding");             // true\ns.compareTo("coding");          // 0'],
  ['Arrays and 2D arrays', 'Use the length field on an array, but length() on a String. Valid indices start at zero. A 2D array contains row arrays.', 'int[] a = {4, 8, 12};\na.length;                       // 3\na[1];                           // 8\nint[][] grid = {{1, 2}, {3, 4}};\ngrid.length;                    // 2 rows\ngrid[0].length;                 // 2 columns in row 0'],
  ['ArrayList methods', 'ArrayList uses size(), get, and set. set returns the old value without changing the size. Indexed add inserts; remove(int) removes by position and returns the old value.', 'ArrayList<String> names = new ArrayList<String>();\nnames.add("Ada");\nnames.add(0, "Grace");\nnames.size();                   // 2\nnames.get(1);                   // "Ada"\nnames.set(1, "Alan");            // returns "Ada"\nnames.remove(0);                // returns "Grace"'],
  ['Wrapper classes', 'Integer and Double wrap primitive values. Generic collections need reference types, so use ArrayList<Integer> rather than a primitive generic argument. Avoid unboxing null.', 'Integer count = 8;\nint value = count.intValue();\nDouble rate = 2.5;\ndouble amount = rate.doubleValue();\nInteger.MAX_VALUE;              // 2147483647\nInteger.MIN_VALUE;              // -2147483648'],
  ['Text files', 'Import File and IOException from java.io and Scanner from java.util. This example belongs inside a method declaring throws IOException. The file must contain valid int tokens.', 'Scanner input = new Scanner(new File("values.txt"));\nint sum = 0;\nwhile (input.hasNext()) sum += input.nextInt();\ninput.close();\nString[] fields = "Ada,4".split(",");'],
  ['Selection, loops, and safety', 'Guard a potentially unsafe operation on the left side of &&. A loop should update toward termination. this refers to an instance receiver and is unavailable in a static method.', 'if (s != null && s.length() > 0) {\n    System.out.println(s);\n}\nfor (int i = 0; i < a.length; i++) {\n    System.out.println(a[i]);\n}'],
];
export default function JavaReferenceScreen() {
  const blocks = sections.flatMap(([title, text, code]) => [{ type: 'heading', value: title }, { type: 'text', value: text }, { type: 'code', value: code }]);
  return <SafeAreaView edges={['bottom']} style={{ flex: 1, backgroundColor: '#fff' }}><ScrollView contentContainerStyle={{ padding: 20 }}><Text style={{ fontFamily: 'Poppins-Regular', lineHeight: 23, marginBottom: 12 }}>Javify study reference with original examples. These expressions illustrate results; they are not all standalone Java statements. This is not the official exam reference sheet.</Text><LessonContent blocks={blocks} /></ScrollView></SafeAreaView>;
}
